const pacienteRouter = require('./pacienteRouter');
const medicoRouter = require('./medicoRouter');
const secretarioRouter = require('./secretarioRouter');
const barrioRouter = require('./barrioRouter');
const ciudadRouter = require('./ciudadRouter');
const visitaRouter = require('./visitaRouter');
const formulacionRouter = require('./formulacionRouter');
const inventarioRouter = require('./inventarioRouter');
const medicamentoRouter = require('./medicamentoRouter');
const laboratorioRouter = require('./laboratorioRouter');
const integranteRouter = require('./integranteRouter');
const contactoRouter = require('./contactoRouter');
module.exports = (app) => {
  app.use('/pacientes', pacienteRouter);
  app.use('/medicos', medicoRouter);
  app.use('/', secretarioRouter);
  app.use('/barrios', barrioRouter);
  app.use('/ciudades', ciudadRouter);
  app.use('/visitas', visitaRouter);
  app.use('/formulaciones', formulacionRouter);
  app.use('/inventarios', inventarioRouter);
  app.use('/medicamentos', medicamentoRouter);
  app.use('/laboratorios', laboratorioRouter);
  app.use('/integrantes', integranteRouter);
  app.use('/contactos', contactoRouter);
};